$ErrorActionPreference = 'Stop'
$project = Split-Path -Parent $PSScriptRoot
$tested = @()
foreach ($file in @('test-windows-installer-lifecycle.ps1', 'test-windows-release-surface.ps1', 'resolve-windows-lifecycle-inputs.ps1')) {
  $tokens = $null
  $errors = $null
  $null = [Management.Automation.Language.Parser]::ParseFile((Join-Path $PSScriptRoot $file), [ref]$tokens, [ref]$errors)
  if ($errors.Count) { throw "PowerShell syntax failure: $file" }
  $tested += "parse:$file"
}
try {
  & (Join-Path $PSScriptRoot 'test-windows-installer-lifecycle.ps1') -PreviousInstaller unused -CurrentInstaller unused -EvidenceDirectory unused -ConfirmDisposableEnvironment:$false
  throw 'Installer guard unexpectedly allowed execution.'
} catch {
  if ($_.Exception.Message -notlike 'Refusing installer mutation*') { throw }
  $tested += 'installer-rejects-missing-confirmation'
}
try {
  & (Join-Path $PSScriptRoot 'test-windows-release-surface.ps1') -Phase Capture -EvidenceDirectory unused -ConfirmDisposableEnvironment:$false
  throw 'Surface guard unexpectedly allowed execution.'
} catch {
  if ($_.Exception.Message -notlike 'Refusing Windows release-surface inspection*') { throw }
  $tested += 'surface-rejects-missing-confirmation'
}
$identity = Get-Content -LiteralPath (Join-Path $project 'release/windows-identity.json') -Raw | ConvertFrom-Json
$version = (Get-Content -LiteralPath (Join-Path $project 'package.json') -Raw | ConvertFrom-Json).version
$tokens = $null
$errors = $null
$ast = [Management.Automation.Language.Parser]::ParseFile((Join-Path $PSScriptRoot 'test-windows-installer-lifecycle.ps1'), [ref]$tokens, [ref]$errors)
$validator = $ast.Find({ param($node) $node -is [Management.Automation.Language.FunctionDefinitionAst] -and $node.Name -eq 'Assert-ManifestArtifact' }, $true)
. ([scriptblock]::Create($validator.Extent.Text))
# Exercise only the read-only manifest validator with inert generated bytes.
# No installer process, disposable flag, actual profile, or registry is used.
$scratch = Join-Path $project '.artifacts/windows-installer-guards'
$null = New-Item -ItemType Directory -Force -Path $scratch
$name = $identity.artifactName.Replace('${version}', $version).Replace('${arch}', [string]$identity.architecture[0]).Replace('${ext}', 'exe')
$fake = Join-Path $scratch $name
[IO.File]::WriteAllText($fake, 'NOT AN EXECUTABLE: generated manifest validation fixture')
$manifestPath = Join-Path $scratch 'release-manifest.json'
$manifest = @{ version=$version; identity=@{installerGuid=$identity.installerGuid}; instrumented=$false; allowlist=@{passed=$true}; signing='unsigned'; publishable=$false; artifacts=@(@{name=$name;sha256=(Get-FileHash -LiteralPath $fake -Algorithm SHA256).Hash}) }
$manifest | ConvertTo-Json -Depth 6 | Set-Content -LiteralPath $manifestPath
Assert-ManifestArtifact $fake $version $false
$tested += 'accepts-exact-unsigned-manifest-hash'
try { Assert-ManifestArtifact $fake $version $true; throw 'Unsigned input accepted as signed.' } catch { if ($_.Exception.Message -notlike 'Signed lifecycle requires*') { throw } }
$tested += 'rejects-unsigned-input-for-signed-lifecycle'
[IO.File]::AppendAllText($fake, 'tampered')
try { Assert-ManifestArtifact $fake $version $false; throw 'Tampered input accepted.' } catch { if ($_.Exception.Message -notlike 'Installer hash does not match*') { throw } }
$tested += 'rejects-tampered-installer-bytes'
[pscustomobject]@{ passed=$true; evidenceClass='source-and-guard-tests'; installerExecuted=$false; profileOrRegistryAccessed=$false; checks=$tested } | ConvertTo-Json
