"""Generate every Pixelody logo file from one geometry.

The mark is the Sampled Disc: a disc (centre 12,12, r 8 on a 24-unit grid)
with one sine cycle, sampled at 12 points and drawn as sample-and-hold steps,
cut out of it. Everything that ships the logo -- desktop icon, window icons,
Android launcher icons, the splash emblem and docs/brand -- is written from
the constants below, so the platforms cannot drift apart.

Run from the repository root:

    pip install shapely fonttools
    python tools/brand/generate_brand_assets.py
    node tools/brand/render_brand_pngs.js   # rasterizes the PNGs

Colours live in LOGO_COLORS. The same list is mirrored by hand in
src/brand-mark.js and android .../ui/brand/PixelodyLogoColor.kt; the render
script and `npm run check` fail if the three disagree.
"""
import json
import math
import os

from shapely.geometry import LineString, MultiPolygon, Point

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), '..', '..'))

# key, display name, hex. The first entry is the brand default.
LOGO_COLORS = [
    ('ultraviolet', 'Ultraviolet', '#6a3dff'),
    ('electric', 'Electric', '#7c5cff'),
    ('indigo', 'Indigo', '#5b5bff'),
    ('grape', 'Grape', '#8a3cf0'),
    ('lavender', 'Lavender', '#a98cff'),
]
GRAPHITE = '#0e0f12'
PAPER = '#f4f4f6'
INK_ON_DARK = '#f5f5f7'
INK_ON_LIGHT = '#111114'

SAMPLES, AMPLITUDE, CUT = 12, 4.5, 1.25          # full-size mark
SMALL_SAMPLES, SMALL_CUT = 8, 1.7                 # 16-24 px mark
SLIVER_AREA = 2.0                                 # drop cut fragments smaller than this


def staircase(samples, amplitude, x0=4.0, x1=20.0, cy=12.0, step=0.5):
    width = (x1 - x0) / samples
    points = [(x0 - 3, cy), (x0, cy)]
    for index in range(samples):
        value = math.sin(2 * math.pi * (index + 0.5) / samples)
        y = cy - round(value * amplitude / step) * step
        points += [(x0 + index * width, y), (x0 + (index + 1) * width, y)]
    return points + [(x1, cy), (x1 + 3, cy)]


def mark_geometry(samples=SAMPLES, cut=CUT, resolution=256):
    disc = Point(12, 12).buffer(8, resolution=resolution)
    wave = LineString(staircase(samples, AMPLITUDE)).buffer(cut / 2, cap_style=2, join_style=2, mitre_limit=10)
    pieces = disc.difference(wave)
    return MultiPolygon([piece for piece in getattr(pieces, 'geoms', [pieces]) if piece.area > SLIVER_AREA])


def path_data(geometry, scale=1.0, dx=0.0, dy=0.0, digits=3):
    out = []
    for polygon in geometry.geoms:
        for ring in [polygon.exterior, *polygon.interiors]:
            coords = list(ring.coords)[:-1]
            out.append('M' + 'L'.join(f'{x * scale + dx:.{digits}f},{y * scale + dy:.{digits}f}' for x, y in coords) + 'Z')
    return ''.join(out)


def write(relative, text):
    target = os.path.join(ROOT, relative)
    os.makedirs(os.path.dirname(target), exist_ok=True)
    with open(target, 'w', encoding='utf-8', newline='\n') as handle:
        handle.write(text)


def tile_svg(mark, ground, color, title, size=512):
    return (f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="{size}" height="{size}">\n'
            f'  <title>{title}</title>\n'
            f'  <rect width="24" height="24" rx="5.25" fill="{ground}"/>\n'
            f'  <path fill="{color}" d="{mark}"/>\n</svg>\n')


def bare_svg(mark, color, title):
    return (f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="4 4 16 16">\n'
            f'  <title>{title}</title>\n  <path fill="{color}" d="{mark}"/>\n</svg>\n')


def android_vector(mark, color, size_dp, viewport):
    return ('<?xml version="1.0" encoding="utf-8"?>\n'
            '<!-- Generated by tools/brand/generate_brand_assets.py. Do not edit by hand. -->\n'
            f'<vector xmlns:android="http://schemas.android.com/apk/res/android"\n'
            f'    android:width="{size_dp}dp"\n    android:height="{size_dp}dp"\n'
            f'    android:viewportWidth="{viewport}"\n    android:viewportHeight="{viewport}">\n'
            f'    <path\n        android:fillColor="{color}"\n        android:pathData="{mark}" />\n'
            '</vector>\n')


def wordmark_path():
    from fontTools.pens.svgPathPen import SVGPathPen
    from fontTools.pens.transformPen import TransformPen
    from fontTools.ttLib import TTFont
    from fontTools.varLib.instancer import instantiateVariableFont
    font = instantiateVariableFont(TTFont(os.path.join(ROOT, 'src/assets/themes/cosmic-cinema/SpaceGrotesk-Variable.ttf')), {'wght': 700})
    glyphs, cmap = font.getGlyphSet(), font.getBestCmap()
    pen, x, tracking = SVGPathPen(glyphs), 0, -20
    for character in 'pixelody':
        name = cmap[ord(character)]
        glyphs[name].draw(TransformPen(pen, (1, 0, 0, -1, x, 0)))
        x += glyphs[name].width + tracking
    return pen.getCommands(), x - tracking


def lockup_svg(mark, word, word_width, color, ink):
    cap = 700
    radius = cap * 0.78
    scale = 2 * radius / 16
    gap = cap * 0.42
    x0 = 2 * radius + gap
    tx, ty = radius - 12 * scale, -cap / 2 - 12 * scale
    top = min(-cap / 2 - radius, -cap - 40)
    bottom = max(-cap / 2 + radius, 230)
    return (f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 {top:.1f} {x0 + word_width:.1f} {bottom - top:.1f}">\n'
            f'  <title>Pixelody</title>\n'
            f'  <path fill="{color}" transform="translate({tx:.2f},{ty:.2f}) scale({scale:.4f})" d="{mark}"/>'
            f'<path fill="{ink}" transform="translate({x0:.1f},0)" d="{word}"/>\n</svg>\n')


def main():
    full = mark_geometry()
    small = mark_geometry(SMALL_SAMPLES, SMALL_CUT)
    mark, mark_small = path_data(full), path_data(small)
    default_hex = LOGO_COLORS[0][2]

    # docs/brand -- the reference set.
    write('docs/brand/pixelody-app-icon.svg', tile_svg(mark, GRAPHITE, default_hex, 'Pixelody application icon'))
    write('docs/brand/pixelody-app-icon-light.svg', tile_svg(mark, PAPER, default_hex, 'Pixelody application icon (light)'))
    write('docs/brand/pixelody-app-icon-small.svg', tile_svg(mark_small, GRAPHITE, default_hex, 'Pixelody application icon (16-24 px)'))
    write('docs/brand/pixelody-mark.svg', bare_svg(mark, default_hex, 'Pixelody mark'))
    write('docs/brand/pixelody-mark-mono.svg', bare_svg(mark, 'currentColor', 'Pixelody mark (single colour)'))
    word, word_width = wordmark_path()
    write('docs/brand/pixelody-wordmark.svg', f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 -760 {word_width:.1f} 1000">\n  <title>Pixelody</title>\n  <path fill="currentColor" d="{word}"/>\n</svg>\n')
    write('docs/brand/pixelody-lockup.svg', lockup_svg(mark, word, word_width, default_hex, INK_ON_DARK))
    write('docs/brand/pixelody-lockup-light.svg', lockup_svg(mark, word, word_width, default_hex, INK_ON_LIGHT))
    for key, _, hex_value in LOGO_COLORS:
        write(f'docs/brand/colors/pixelody-app-icon-{key}.svg', tile_svg(mark, GRAPHITE, hex_value, f'Pixelody application icon ({key})'))

    # Desktop: packaged build icon and the in-app mark (tinted with a CSS mask).
    write('build/icon.svg', tile_svg(mark, GRAPHITE, default_hex, 'Pixelody application icon'))
    write('src/assets/brand/pixelody-mark.svg', bare_svg(mark, '#000', 'Pixelody mark'))
    write('src/assets/brand/pixelody-mark-small.svg', bare_svg(mark_small, '#000', 'Pixelody mark (small)'))
    # Window/taskbar icons are rasterized from docs/brand/colors/*.svg into
    # src/assets/brand/window-icon-<key>.png by render_brand_pngs.js.

    # Android: adaptive-icon foregrounds (108 dp canvas, mark inside the 66 dp
    # safe zone), one per colour, plus the splash emblem.
    res = 'android/app/src/main/res'
    scale = 60 / 16                     # 16-unit disc -> 60 dp
    offset = 54 - 12 * scale            # centre on 54,54
    launcher_mark = path_data(full, scale, offset, offset, 2)
    for key, _, hex_value in LOGO_COLORS:
        write(f'{res}/drawable/ic_launcher_foreground_{key}.xml', android_vector(launcher_mark, hex_value, 108, 108))
        write(f'{res}/mipmap-anydpi-v26/ic_launcher_{key}.xml',
              '<?xml version="1.0" encoding="utf-8"?>\n'
              '<!-- Generated by tools/brand/generate_brand_assets.py. Do not edit by hand. -->\n'
              '<adaptive-icon xmlns:android="http://schemas.android.com/apk/res/android">\n'
              '    <background android:drawable="@color/pixelody_brand_graphite" />\n'
              f'    <foreground android:drawable="@drawable/ic_launcher_foreground_{key}" />\n'
              f'    <monochrome android:drawable="@drawable/ic_launcher_foreground_{key}" />\n'
              '</adaptive-icon>\n')
    write(f'{res}/drawable/splash_brand_emblem.xml', android_vector(path_data(full, 1, -4, -4, 3), default_hex, 160, 16))
    write(f'{res}/values/brand_colors.xml',
          '<?xml version="1.0" encoding="utf-8"?>\n'
          '<!-- Generated by tools/brand/generate_brand_assets.py. Do not edit by hand. -->\n<resources>\n'
          f'    <color name="pixelody_brand_graphite">{GRAPHITE}</color>\n'
          + ''.join(f'    <color name="pixelody_logo_{key}">{hex_value}</color>\n' for key, _, hex_value in LOGO_COLORS)
          + '</resources>\n')

    write('tools/brand/logo-colors.json', json.dumps([{'key': k, 'name': n, 'hex': h} for k, n, h in LOGO_COLORS], indent=2) + '\n')
    print(f'Wrote brand assets for {len(LOGO_COLORS)} colours.')


if __name__ == '__main__':
    main()
